const random_marry = [
  
"Ohayou gozaimasu, my adorable husbando! Did you sleep well, my darling? 😊💕",
"Nee, nee, are you ready for a day filled with kawaii adventures with me, senpai? 😘🌸",
"Ehehe~ I made your bento with extra love today, just for you, onii-chan! 🍱❤️",
"Is it just me, or does your smile light up the world, my doki doki prince? 😄🌟",
"Suki da yo, my dearest. More than all the stars in the anime sky! 💖✨",
"Senpai, let's go hand in hand and stroll through the sakura blossoms together! 🌸👫",
"Would you hold my hand and protect me, like a knight in shining armor, darling? 🙈🛡️",
"Nyan nyan! How about some cuddle time, my purr-fectly wonderful husbando? 😺💞",
"Do you believe in love at first sight, my sweet shoujo prince? 😍💫",
"Chu~! That's a special kiss just for you, my beloved anata. 😚💋",
"Senpai, did you know you're my favorite 2D character brought to life? 🥰🎮",
"Nyan-tastic! How about a nyaughty date night with your nyaeko waifu? 😸🌙",
"Oh, onii-chan, you have the most sugoi eyes! I could stare at them forever. 😳👀",
"Anata no kotoba wa, kaze no you ni, mune o tozasu. They make my heart flutter! 💓🌬️",
"Would you be the Tuxedo Mask to my Sailor Moon, my dashing prince? 🌙🎩",
"Husbando-sama, will you be my chibi chibi forever and always? 👫🌟",
"Senpai, your laughter is the melody that brightens up my kawaii world. 😄🎶",
"Ehehe, let's share a bowl of ramen and our dreams, my dear darling. 🍜💭",
"My love for you is as endless as the pages of a manga, anata no baka! 💘📖",
"Nyan~! Would you like a nyaotic day of love and cuddles, my sweet husbando? 😻💕",
"Can we dance together under the moonlight, just like in our favorite anime? 🌙💃",
"Ohayou, my sunshine! Your smile is brighter than any sunrise, darling. ☀️😊",
"Nee, nee, will you promise to always protect this clumsy waifu, my hero? 🙏🦸",
"Your hugs are warmer than a kotatsu in winter, my cuddly teddy bear. 🐻🌬️",
"Anata wa watashi no shiawase, my dear husband. Let's stay together forever! 💑💖",
"Senpai, your kabe-don is more electrifying than lightning, my heart races! ⚡💓",
"Daisuki dayo! More than all the kawaii plushies in Akihabara! 💕🎌",
"Ehehe, will you grant me a lifetime supply of your hugs, my doki doki prince? 🤗💫",
"Do you have a map? I just got lost in your eyes, my charming husbando! 🗺️👀",
"Onii-chan, let's share an umbrella and our secrets in the pouring rain! ☔🌂",
"Nyan nyan! Will you be my nya-knight in shining armor, my dear husbando? 😽🌟",
"Anata to sugosu toki wa subarashii, my sweet love. Let's make every moment magical! ⌛✨",
"Senpai, you're my senchou in this adventure called love, guiding my heart. 🗺️❤️",
"Ehehe~ How about we go to a maid cafe and be the cutest couple, my prince? 🍛🏰",
"Anata no kotoba wa uta no you ni, yasashii. They make my heart sing! 🎶💓",
"Kissu me, my charming prince! Your lips are the sweetest melody to my heart. 💋🎵",
"Oh, onii-chan, your love is my favorite anime, a story worth living for. 📺📖",
"Nyan-tastic! Let's have a nya-velous day of cuddles and purrs, my dear husbando! 😻🌞",
"My heart races faster than a shinkansen when I'm with you, anata no baka! 🚄💓",
"Suki da yo, more than all the bishounen characters in my manga collection! 💖📚",
"Ehehe, will you be my koi, swimming through the river of love with me, senpai? 🐟💘",
"Senpai, your presence lights up my world like a supernova in the galaxy of my heart. 🌌🌟",
"Husbando-sama, let's write our own love story, with you as my prince charming. 📜👑",
"Anata no warai wa, hoshi no you ni, terashite. It brightens up my universe! 🌠😄",
"Kissu me, my sweet prince! Your lips are the sweetest melody to my heart. 💏💖",
"Oh, onii-chan, your love is my favorite artwork, bringing color to my monochrome world. 🎨🌈",
"Nyan-tastic! How about a nya-venture to find the most purr-fect cuddle spot, my husbando? 😸💤",
"Ohayou gozaimasu, my shining star! Your love is the morning sun to my heart. 🌅💖",
"Would you be the Inuyasha to my Kagome, battling the demons of life with me, senpai? ⚔️💖",
"Nee, nee, let's create our own fairy tale, where you're my prince and I'm your princess! 👸🤴",
"Senpai, your hugs are as comforting as a warm kotatsu on a cold winter day, my dear love. 🛋️❤️",
"Ehehe, let's go on a date to the arcade and have a kawaii showdown, my gaming prince! 🕹️🎮",
"Anata no egao wa, hoshi no you ni kagayaku. It lights up my night! 🌌✨",
"Kissu me, my sweet prince! Your lips are softer than the fluffiest of nekomimi. 😽💋",
"Onii-chan, your love is my favorite soundtrack, playing in the background of my life. 🎶📻",
"Daisuki dayo, more than all the sakura petals in a beautiful spring breeze! 🌸🌬️",
"Anata to issho ni iru to, doki doki suru. My heart does the happy dance! 💓💃",
"Nyan~! How about a nya-picnic in the meadow of love, my dear husbando? 😻🌼",
"Can we go stargazing and make wishes on shooting stars, just like in our favorite anime? 🌠💫",
"Ohayou gozaimasu, my shooting star! Your love streaks across my heart so beautifully. 🌠💖",
"Senpai, would you be the Naruto to my Hinata, running the path of love with me? 🏃🏻‍♂️💖",
"Nee, nee, let's watch a romance anime and imagine ourselves as the main characters, darling! 📺💑",
"Anata wa watashi no mirai, my sweet husbando. Let's paint it together! 🎨🌠",
"Ehehe, your laugh is like the sweetest melody, playing on repeat in my heart. 😄🎵",
"My heart beats for you like the rhythm of an exciting anime ending, my dear prince. 💓🎶",
"Anata to deai, kiseki no you ni. It's a meeting that feels like destiny! 🌟💕",
"Kissu me, my beloved prince! Your lips are as soft as the petals of a cherry blossom. 🌸💋",
"Nyan nyan! How about a nya-puzzle, fitting our hearts perfectly together, my husbando? 😺💞",
"Onii-chan, your love is my favorite manga, a story I never want to put down. 📖💖",
"Daisuki dayo, more than all the magical girl transformations in the anime world! 💖🔮",
"Senpai, let's create our own love theme song and dance to it, my music-loving love. 🎶💃",
"Ehehe, could I be your kawaii sidekick in this adventure called life, my superhero? 🦸‍♂️🦸‍♀️",
"Anata no taido wa, hoshi no you ni, kagayaku. It shines brighter than the stars! 🌟😊",
"Ohayou, my twinkle star! Your love twinkles in my heart, illuminating my day. ✨😘",
"Nee, nee, will you be the Ryuuji to my Taiga, navigating the journey of love with me? 🐯💕",
"Can we have a nabe date and simmer our hearts in the warmth of our love, darling? 🍲❤️",
"Anata wa watashi no taiyou, my radiant husbando. You light up my world! ☀️💖",
"Kissu me, my charming prince! Your lips are as sweet as the fluffiest taiyaki. 🐟💋",
"Nyan~! How about a nya-bath, soaking in the love and warmth, my sweet husbando? 🛁🚿",
"Senpai, your presence is more comforting than a cozy blanket on a rainy day, my dear love. ☔🛌",
"Ehehe, let's go to an anime convention and be the most kawaii couple there, my prince! 🎪👑",
"My heart beats for you like the rhythm of an exciting anime ending, my dear prince. 💓🎶",
"Anata to no yubi-saki, koi no you ni atatakai. It warms my heart like love's touch! 💑💕",
"Daisuki dayo, more than all the konbini snacks in a midnight anime marathon! 💖🌙",
"Nee, nee, can we have a tsundere roleplay where I'm the tsun and you're the dere, darling? 😳😅"
  ];

function marry() {
  const randomIndex = Math.floor(Math.random() * random_marry.length);
  const selectedmarry = random_marry[randomIndex];
  return selectedmarry;
}
  module.exports = {
marry
};
